image: ghcr.io/robotology/icub-gazebo-grasping-sandbox:latest
github:
  prebuilds:
    master: false
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false
ports:
- port: 6080
  onOpen: notify
- port: 10000-20000
  onOpen: ignore
tasks:
- command: start-vnc-session.sh
- command: gp await-port 6080 && gp preview $(gp url 6080)
